SET IDENTITY_INSERT [dbo].[Products] ON
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (1, N'ASUS Corei7', CAST(1000.000 AS Decimal(12, 3)), N'Notebook')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (2, N'Samsung', CAST(900.000 AS Decimal(12, 3)), N'Phone')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (3, N'iPhone', CAST(1200.000 AS Decimal(12, 3)), N'Phone')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (4, N'Samsung TV', CAST(500.000 AS Decimal(12, 3)), N'TV')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (5, N'LG TV', CAST(600.000 AS Decimal(12, 3)), N'TV')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (6, N'HP', CAST(550.000 AS Decimal(12, 3)), N'Notebook')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (8, N'MI', CAST(400.000 AS Decimal(12, 3)), N'Phone')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (9, N'Lenovo', CAST(1400.000 AS Decimal(12, 3)), N'Notebook')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (13, N'Lenovo', CAST(400.000 AS Decimal(12, 3)), N'Notebook')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (14, N'Samsung A30', CAST(200.000 AS Decimal(12, 3)), N'Phone')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (15, N'Lenovo', CAST(1400.000 AS Decimal(12, 3)), N'Notebook')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (16, N'Mouse', CAST(15.000 AS Decimal(12, 3)), N'Accessories')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (17, N'Lenovo', CAST(1400.000 AS Decimal(12, 3)), N'Notebook')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (18, N'Mouse', CAST(15.000 AS Decimal(12, 3)), N'Accessories')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (19, N'Lenovo', CAST(1400.000 AS Decimal(12, 3)), N'Notebook')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (20, N'Mouse', CAST(15.000 AS Decimal(12, 3)), N'Accessories')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (21, N'Lenovo', CAST(1400.000 AS Decimal(12, 3)), N'Notebook')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (22, N'Mouse', CAST(15.000 AS Decimal(12, 3)), N'Accessories')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (23, N'Lenovo', CAST(1400.000 AS Decimal(12, 3)), N'Notebook')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (24, N'Mouse', CAST(15.000 AS Decimal(12, 3)), N'Accessories')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (25, N'Lenovo', CAST(1400.000 AS Decimal(12, 3)), N'Notebook')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (26, N'Mouse', CAST(15.000 AS Decimal(12, 3)), N'Accessories')
INSERT INTO [dbo].[Products] ([Id], [Name], [Price], [Category]) VALUES (27, N'Lenovo', CAST(500.000 AS Decimal(12, 3)), N'Tablet')
SET IDENTITY_INSERT [dbo].[Products] OFF
