//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
         /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Catalog.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products
        {
            get
            {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories
        {
            get
            {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs
        {
            get
            {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AppName.
        /// </summary>
        public static string AppName
        {
            get
            {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        public static string BackToList
        {
            get
            {
                return ResourceManager.GetString("Back To List", resourceCulture);
            }
        }

        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        public static string UserName
        {
            get
            {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }

        public static string FirstName
        {
            get
            {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        public static string FillAllFiels
        {
            get
            {
                return ResourceManager.GetString("Fill All Fields", resourceCulture);
            }
        }

        public static string LastName
        {
            get
            {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        public static string Password
        {
            get
            {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        public static string ConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }

        public static string Activation
        {
            get
            {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }

        public static string ActivationCode
        {
            get
            {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }

        public static string Activate
        {
            get
            {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }

        public static string ModelError
        {
            get
            {
                return ResourceManager.GetString("ModelError", resourceCulture);
            }
        }

        public static string WrongCredentials
        {
            get
            {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }

        public static string ActivationFailed
        {
            get
            {
                return ResourceManager.GetString("ActivationFailed", resourceCulture);
            }
        }

        public static string PasswordsShouldMatch
        {
            get
            {
                return ResourceManager.GetString("PasswordsShouldMatch", resourceCulture);
            }
        }

        public static string UserNameExists
        {
            get
            {
                return ResourceManager.GetString("User name already exists", resourceCulture);
            }
        }

        public static string RegistrationFailed
        {
            get
            {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }

        public static string RegistrationCompleted
        {
            get
            {
                return ResourceManager.GetString("RegistrationCompleted", resourceCulture);
            }
        }
        public static string PhoneNumber
        {
            get
            {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        public static string Sort
        {
            get
            {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }


    }
}
